# Generated by Django 5.1.4 on 2024-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("sport", models.CharField(max_length=64)),
                ("location", models.CharField(max_length=128)),
                ("desc", models.TextField()),
                ("dateTime", models.DateField()),
            ],
        ),
    ]
