# Generated by Django 5.1.4 on 2024-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create", "0002_rename_name_events_eventname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="dateTime",
            new_name="date",
        ),
    ]
